module.exports = {
  locals: {
    data: {
      project_title: 'Railsware HTML/CSS Test Task',
      days_of_week: [
        'sun', 'mon',
        'tue', 'wed',
        'thu', 'fri',
        'sat',
      ],

      calendar_days: {
        1: {},
        2: {},
        3: {},
        4: {},
        5: {},
        6: {},
        7: {},
        8: {},
        9: {},
        10: {},
        11: {},
        12: {},
        13: {},
        14: {},
        15: {},
        16: {},
        17: {},
        18: {},
        19: { isAvailable: true, isToday: true },
        20: { isAvailable: true },
        21: {},
        22: {},
        23: { isAvailable: true },
        24: { isAvailable: true },
        25: { isAvailable: true },
        26: { isAvailable: true },
        27: { isAvailable: true },
        28: {},
        29: {},
        30: { isAvailable: true },
      },

      time_spots: [
        '09:00', '09:30',
        '10:00', '10:30',
        '11:00', '11:30',
        '12:00', '12:30',
        '13:00', '13:30',
      ],
      invitee: 'WebSummit',
      meeting_name: 'Local Meetup',
      meeting_interval: '15 min',
      location: 'Lisbon, Portugal',
      description: 'Local Meetup for Entrepreneurs',
      booking_title: 'Select a Date & Time',
      currentMonth: 'September',
      currentYear: '2019',
      pickedDayOfWeek: 'Friday',
      pickedMonth: 'September',
      currentTimezone: 'UK, Ireland, Lisbon Time (09:43)',
      timezones_list: [
        'Israel Time (10:43)',
        'Japan, Korea Time (16:43)',
      ],
      confirm_btn: 'Confirm',
    },
  },
};
